# Docker Compose for Manus AI Platform
# Development and production configurations

version: '3.8'

services:
  # Main application
  manus-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ENVIRONMENT=production
      - PORT=5001
      - WORKERS=4
      - MAX_UPLOAD_SIZE=524288000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - uploads:/tmp/manus_uploads
      - workspace:/tmp/manus_workspace
      - logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - manus-platform
    restart: unless-stopped
    profiles:
      - production

volumes:
  uploads:
  workspace:
  logs:
  redis_data:

networks:
  default:
    name: manus-network

